# Generated by Django 5.0.7 on 2024-08-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepost",
            name="total_views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
