# Generated by Django 5.0.7 on 2024-08-12 02:47

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0005_articlepost_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepost",
            name="avatar",
            field=imagekit.models.fields.ProcessedImageField(
                upload_to="article/%Y%m%d"
            ),
        ),
    ]
