# Generated by Django 5.0.7 on 2024-08-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0006_alter_articlepost_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepost",
            name="avatar",
            field=models.ImageField(blank=True, upload_to="article/%Y%m%d/"),
        ),
    ]
