# Generated by Django 5.0.7 on 2024-08-13 09:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
